# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rake-tui 0.2.1 ruby lib

Gem::Specification.new do |s|
  s.name = "rake-tui".freeze
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["andy_maleh".freeze]
  s.date = "2020-09-07"
  s.description = "Rake Text-based User Interface".freeze
  s.email = "andy.am@gmail.com".freeze
  s.executables = ["rake-tui".freeze, "jrake-tui".freeze, "raketui".freeze, "jraketui".freeze, "rake-ui".freeze, "jrake-ui".freeze, "rakeui".freeze, "jrakeui".freeze]
  s.extra_rdoc_files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "CHANGELOG.md",
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "bin/jrake-tui",
    "bin/jrake-ui",
    "bin/jraketui",
    "bin/jrakeui",
    "bin/rake-tui",
    "bin/rake-ui",
    "bin/raketui",
    "bin/rakeui",
    "lib/rake-tui.rb",
    "lib/rake-tui/ext/rake/tui.rb"
  ]
  s.homepage = "http://github.com/AndyObtiva/rake-tui".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.1.4".freeze
  s.summary = "Rake TUI".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_runtime_dependency(%q<tty-prompt>.freeze, [">= 0"])
    s.add_development_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_development_dependency(%q<bundler>.freeze, [">= 1.0"])
    s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_development_dependency(%q<e2mmap>.freeze, ["~> 0.1.0"])
    s.add_development_dependency(%q<puts_debuggerer>.freeze, [">= 0"])
  else
    s.add_dependency(%q<tty-prompt>.freeze, [">= 0"])
    s.add_dependency(%q<rspec>.freeze, ["~> 3.5.0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.0"])
    s.add_dependency(%q<juwelier>.freeze, ["~> 2.1.0"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<e2mmap>.freeze, ["~> 0.1.0"])
    s.add_dependency(%q<puts_debuggerer>.freeze, [">= 0"])
  end
end

